name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# GitHub Pages deployment note
# This project is configured to automatically deploy from the docs directory
# Make sure GitHub Pages is enabled in repository settings with the following options:
# - Source: Deploy from a branch
# - Branch: main
# - Folder: /docs

# The deploy-worker job has been removed as the user is deploying manually from terminal
# using commands like: npx wrangler deploy 

jobs:
  # GitHub Pages is automatically deployed from the docs directory
  # when configured in the repository settings
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: No actions needed
        run: echo "Manual deployment is being used for Cloudflare Workers. GitHub Pages deploys automatically."

# Note: Cloudflare Worker deployment is done manually from terminal using:
# npx wrangler deploy 