name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Install Wrangler
        run: npm install -g wrangler
      - name: Deploy Worker
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

  # GitHub Pages deployment note
  # This project is configured to automatically deploy from the docs directory
  # Make sure GitHub Pages is enabled in repository settings with the following options:
  # - Source: Deploy from a branch
  # - Branch: main
  # - Folder: /docs 